### ISSUE TITLE
Unit test Failed: Error while reading resource variable from Container

### ISSUE THREAD

**Issue by maye9999** [haowen-xu/donut#2]
Hello, I'm trying to run the unit test in `test_prediction.py`. However, it doesn't seem to pass the unittest.

The enviroment of my computer is Python2.7 + Tensorflow 1.9.

Thank you very much and looking foward to your reply.

```text
2018-07-20 08:44:39.242085: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
E.
======================================================================
ERROR: test_prediction (__main__.DonutPredictorTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_prediction.py", line 37, in test_prediction
    res = pred.get_score(values=np.arange(5, dtype=np.float32))
  File "/usr/local/lib/python2.7/dist-packages/donut/prediction.py", line 145, in get_score
    feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
FailedPreconditionError: Error while reading resource variable donut/p_x_given_z/forward_1/std/dense_5/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/donut/p_x_given_z/forward_1/std/dense_5/kernel/N10tensorflow3VarE does not exist.
         [[Node: donut/p_x_given_z/forward_1/std/dense_5/Tensordot/ReadVariableOp = ReadVariableOp[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](donut/p_x_given_z/forward_1/std/dense_5/kernel)]]

Caused by op u'donut/p_x_given_z/forward_1/std/dense_5/Tensordot/ReadVariableOp', defined at:
  File "tests/test_prediction.py", line 88, in <module>
    tf.test.main()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/test.py", line 64, in main
    return _googletest.main(argv)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/googletest.py", line 100, in main
    benchmark.benchmarks_main(true_main=main_wrapper)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/benchmark.py", line 344, in benchmarks_main
    true_main()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/googletest.py", line 99, in main_wrapper
    return app.run(main=g_main, argv=args)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/googletest.py", line 70, in g_main
    return unittest_main(argv=argv)
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/lib/python2.7/unittest/main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/lib/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "tests/test_prediction.py", line 37, in test_prediction
    res = pred.get_score(values=np.arange(5, dtype=np.float32))
  File "/usr/local/lib/python2.7/dist-packages/donut/prediction.py", line 144, in get_score
    b_r = sess.run(self._get_score_without_y(),
  File "/usr/local/lib/python2.7/dist-packages/donut/prediction.py", line 80, in _get_score_without_y
    last_point_only=self._last_point_only
  File "/usr/local/lib/python2.7/dist-packages/donut/model.py", line 198, in get_score
    p_net = self.vae.model(z=q_net['z'], x=x, n_z=n_z)  # notice: x=x
  File "/usr/local/lib/python2.7/dist-packages/tfsnippet/utils/reuse.py", line 179, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tfsnippet/modules/auto_encoders/vae.py", line 314, in model
    x_params = self.h_for_p_x(z)
  File "/usr/local/lib/python2.7/dist-packages/tfsnippet/modules/base.py", line 89, in __call__
    return self._forward(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tfsnippet/modules/container/sequential.py", line 78, in _forward
    outputs = c(outputs)
  File "/usr/local/lib/python2.7/dist-packages/tfsnippet/modules/base.py", line 89, in __call__
    return self._forward(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tfsnippet/modules/container/branch.py", line 126, in _forward
    ret[k] = v(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/donut/model.py", line 68, in <lambda>
    )(x)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 703, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/layers/core.py", line 910, in call
    [0]])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 2898, in tensordot
    b = ops.convert_to_tensor(b, name="b")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1011, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1107, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 1031, in _dense_var_to_tensor
    return var._dense_var_to_tensor(dtype=dtype, name=name, as_ref=as_ref)  # pylint: disable=protected-access
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 982, in _dense_var_to_tensor
    return self.value()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 659, in value
    return self._read_variable_op()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 742, in _read_variable_op
    self._dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_resource_variable_ops.py", line 507, in read_variable_op
    "ReadVariableOp", resource=resource, dtype=dtype, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): Error while reading resource variable donut/p_x_given_z/forward_1/std/dense_5/kernel from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/donut/p_x_given_z/forward_1/std/dense_5/kernel/N10tensorflow3VarE does not exist.
         [[Node: donut/p_x_given_z/forward_1/std/dense_5/Tensordot/ReadVariableOp = ReadVariableOp[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](donut/p_x_given_z/forward_1/std/dense_5/kernel)]]


----------------------------------------------------------------------
Ran 2 tests in 0.263s

FAILED (errors=1)
```

**Comment by maye9999** [comment]
I downgrade Tensorflow to 1.8 and it works. So maybe some API changed in 1.9?

However, when I run the file `test_model.py` on Tensorflow 1.8, some new error occurs.

```text
....F
======================================================================
FAIL: test_variable_reuse (__main__.ModelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_model.py", line 55, in test_variable_reuse
    'get_donut/donut/q_z_given_x/z_std/kernel']
AssertionError: Lists differ: [u'get_donut/donut/p_x_given_z... != ['get_donut/donut/p_x_given_z/...

First differing element 0:
u'get_donut/donut/p_x_given_z/mean/dense/bias'
'get_donut/donut/p_x_given_z/x_mean/bias'

Diff is 1428 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 6 tests in 1.048s

FAILED (failures=1)
```

Could you please check it too? Thank you very much!

**Comment by haowen-xu** [comment]
Actually the Python 2.7 + TensorFlow 1.8 already passes unit tests on Travis CI (https://travis-ci.org/haowen-xu/donut/jobs/406086706).

It seems to be related to a bug I fixed today (see https://github.com/haowen-xu/donut/commit/bef55755b001c31da4f5b15963f94df43f36b87c), which has been existing long before I noticed it.  The old version would construct a set of new variables each time the encoder or decoder of the model is built, but I meant to reuse the previous constructed ones.  You may upgrade to the newest version to have a try.

If you just cloned it from git, do ``git pull``.  Otherwise if you also installed it, please do ``pip install --upgrade git+https://github.com/haowen-xu/donut.git``.

**Comment by maye9999** [comment]
Thanks for your reply.

By the way, I'd like to ask some questions about the inputs of the model.

* The `values` for `DonutTrainer.fit` and `DonutPredictor.get_score` is 1-D vector and do I need to handle the sliding window? Or the sliding windows is handled internally in Trainer and Predictor?
* When I don't have missing points, could I just set the `missing` to zeros_like(values)?
* The readme says `If there is no label, simply use all zeros`. I assume VAE models are un-supervised, so I don't understand the usage of labels in `DonutTrainer.fit`. Is it simply used for evaluate the model, or is it involved in some training process?

Thank you very much and looking foward to your reply!

**Comment by haowen-xu** [comment]
@maye9999 Better close the current issue and start a new one, since it might be helpful to other participants.  If you do so, I will copy and paste this comment to the new issue.

- Yes, it will handle the sliding windows internally.  The reason of this is that Donut applies missing data injection, which might be better applied on the original 1-D series, rather than the sliding windows.
- Yes, you can.  Also, you need to pass in numpy arrays, not TensorFlow tensors.
- As the training goes by, the std estimation of ``q(z|x)`` and ``p(x|z)`` would probably decrease to a very small value, such that if an unlabelled anomaly presents in the training data, it will cause severe confusion to the gradient at that point (recall that ``log Normal(..)`` contains a ``-(x-mean)/std^2`` term).  So if you have labels, it will definitely help to stabilize training, thus make the model converge to a better local optimum.  When you do not have labels, the missing data injection part of the algorithm will help the model gain some ability to adapt to such noises.  And with the help of some other techniques (e.g., gradient clip by norm), the algorithm can still work to some extent.
